### ISSUE TITLE
Package Says it Requires UdonSharp Despite Being Combined With VRChat Worlds Package

### ISSUE THREAD

**Issue by ghost** [emymin/EmyChess#10]
The most recent release of VRChat's world package says that it requires a specific version of udonsharp despite being combined with the world package. I wanted to ensure that the package did get resolved. This issue isn't major as it works perfectly outside of it being considered an unresolved package.

**Comment by BluWizard10** [comment]
I have already opened a PR that directly fixes this issue. Please take a look: https://github.com/emymin/EmyChess/pull/11

**Comment by emymin** [comment]
@BluWizard10 's PR fixes the issue!
