### ISSUE TITLE
pawn queen swap broken.

### ISSUE THREAD

**Issue by DJJeffP** [emymin/EmyChess#2]
when the queen is of the table and a pawn to the end of the board at opponent side, the pawn to queen swap broke. the opponent gets his color queen instead of mine. but the whole game also broke and no turns can be made any more.

**Comment by emymin** [comment]
Hello! May I get some additional information to help reproduce this bug? Such as the board layout, if it was anarchy/regular chess, wheter this was the first pawn promotion, any info I could use to see if I can reproduce the issue
