### ISSUE TITLE
[SOLVED] [V.0.0.1] udon scripts not attatched to prefab

### ISSUE THREAD

**Issue by X4ndras** [emymin/EmyChess#3]

**Comment by emymin** [comment]
Hello! Can I get some additional information? Are there no udon scripts at all, or there are but they have errors? In the second case, did you try following the fix at the end of the "Setup" section in the readme?

**Comment by X4ndras** [comment]
Hi i fixed it my problem was that there was something wrong with my Unity project i created a new one and imported EmyChess again in the new project now it works totally fine.
