### ISSUE TITLE
How do i make it work 

### ISSUE THREAD

**Issue by ssshammi** [emymin/EmyChess#4]
I have downloaded the UdonSharp and Vrchat . but its not functional, should I reconfigure all of these?
![image](https://user-images.githubusercontent.com/2300969/184656817-1c554183-9885-4233-835a-6d765b7062cb.png)

**Comment by emymin** [comment]
The prefab is supposed to be functional on import without any tweaking, so if it isn't then something went wrong. If you clear Unity's log, do any errors remain?

**Comment by ssshammi** [comment]
Thanks for the quick response , I opened the prefab and the references were missing'. @emymin 
I also made a video of what's going on. https://youtu.be/tu3oNTIF1Bc
![image](https://user-images.githubusercontent.com/2300969/184670860-ba631bc3-b7d3-4df9-a0c4-9b0f8f82b41a.png)
 

UdonBehaviour 'PromotionPicker (VRC.Udon.UdonBehaviour)' needs upgrade on source prefab asset.
UnityEngine.Debug:LogWarning (object,UnityEngine.Object)
UdonSharp.UdonSharpUtils:LogWarning (object,UnityEngine.Object) (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/UdonSharpUtils.cs:311)
UdonSharpEditor.UdonSharpBehaviourEditor:OnEnable () (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/Editors/UdonSharpBehaviourEditor.cs:162)
UnityEditor.Editor:CreateEditor (UnityEngine.Object,System.Type)
VRC.Udon.Editor.UserInspectorManager:GetCustomEditor (UnityEditor.Editor) (at D:/unity stuff/My project (2)/Assets/Udon/Editor/UdonBehaviourEditor.cs:465)
VRC.Udon.Editor.UserInspectorManager:DoRequiresConstantRepaint (UnityEditor.Editor,bool&) (at D:/unity stuff/My project (2)/Assets/Udon/Editor/UdonBehaviourEditor.cs:409)
VRC.Udon.Editor.UdonBehaviourEditor:RequiresConstantRepaint () (at D:/unity stuff/My project (2)/Assets/Udon/Editor/UdonBehaviourEditor.cs:213)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by ssshammi** [comment]
The chess pieces are not getting placed for some reason. 
I used VRCSDK3-WORLD-2022.06.03.00.03_Public.unitypackage and
UdonSharp_v0.20.3.unitypackage
and 
`NullReferenceException: Object reference not set to an instance of an object
Emychess.BoardInspector.GeneratePools (Emychess.Board board, System.Collections.Generic.Dictionary`2[TKey,TValue] pieceDict) (at Assets/EmyChess/EmyChess/Scripts/Board.cs:598)
Emychess.BoardInspector.OnInspectorGUI () (at Assets/EmyChess/EmyChess/Scripts/Board.cs:683)
UdonSharpEditor.UdonSharpBehaviourOverrideEditor.<CreateCustomInspectorElement>b__12_3 () (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/Editors/UdonSharpBehaviourEditor.cs:672)
UdonSharpEditor.UdonSharpBehaviourOverrideEditor+<>c__DisplayClass16_0.<CreateIMGUIInspector>b__0 () (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/Editors/UdonSharpBehaviourEditor.cs:728)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <344226e341014466b33f0c0fa34fcef5>:0)
`

**Comment by ssshammi** [comment]
`UdonSharp] Empty UdonBehaviour found on pawn0 (UnityEngine.GameObject)
UnityEngine.Debug:LogWarning (object,UnityEngine.Object)
UdonSharp.UdonSharpUtils:LogWarning (object,UnityEngine.Object) (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/UdonSharpUtils.cs:311)
UdonSharpEditor.UdonSharpEditorManager:RepairProgramAssetLinks (System.Collections.Generic.List`1<VRC.Udon.UdonBehaviour>) (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/UdonSharpEditorManager.cs:1271)
UdonSharpEditor.UdonSharpEditorManager:RunAllUpdates (System.Collections.Generic.List`1<VRC.Udon.UdonBehaviour>) (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/UdonSharpEditorManager.cs:728)
UdonSharpEditor.UdonSharpEditorManager:RunPostBuildSceneFixup () (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/UdonSharpEditorManager.cs:108)
UdonSharp.Compiler.UdonSharpCompilerV1:TickCompile () (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/Compiler/UdonSharpCompilerV1.cs:187)
UdonSharp.Compiler.UdonSharpCompilerV1:WaitForCompile () (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/Compiler/UdonSharpCompilerV1.cs:220)
UdonSharp.Compiler.UdonSharpCompilerV1:CompileSync (UdonSharp.Compiler.UdonSharpCompileOptions) (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/Compiler/UdonSharpCompilerV1.cs:242)
UdonSharpEditor.UdonSharpBuildCompile:OnBuildRequested (VRC.SDKBase.Editor.BuildPipeline.VRCSDKRequestedBuildType) (at D:/unity stuff/My project (2)/Packages/com.vrchat.UdonSharp/Editor/BuildUtilities/UdonSharpBuildCompile.cs:20)
VRC.SDKBase.Editor.BuildPipeline.VRCBuildPipelineCallbacks:OnVRCSDKBuildRequested (VRC.SDKBase.Editor.BuildPipeline.VRCSDKRequestedBuildType)
VRC.SDK3.Editor.VRCSdkControlPanelWorldBuilder3:OnGUIScene () (at Assets/VRCSDK/SDK3/Editor/VRCSdkControlPanelWorldBuilder3.cs:173)
VRC.SDKBase.Editor.VRCSdkControlPanelWorldBuilder:ShowBuilder () (at Assets/VRCSDK/Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanelWorldBuilder.cs:130)
VRC.SDK3.Editor.VRCSdkControlPanelWorldBuilder3:ShowBuilder () (at Assets/VRCSDK/SDK3/Editor/VRCSdkControlPanelWorldBuilder3.cs:43)
VRCSdkControlPanel:ShowBuilders () (at Assets/VRCSDK/Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanelBuilder.cs:329)
VRCSdkControlPanel:OnGUI () (at Assets/VRCSDK/Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanel.cs:214)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)`

**Comment by emymin** [comment]
This is actually an issue that I ran into when importing another prefab created before U# 1.0 in a project created with the VRChat Creator Companion app. Sadly I don't remember exactly how I fixed it, I think it was either deleting the prefab's folder and reimporting it, or re-compiling all U# scripts.

**Comment by ssshammi** [comment]
Got it working thanks

**Comment by EasyMochi** [comment]
Care to explain how exactly? I've been having the same issue, and I'm sure other people do. Would be nice to explain how you fixed it so that when other people spend hours trying to fix something, they can find a possible solution. Thanks!
