### ISSUE TITLE
Broken with the new VCC

### ISSUE THREAD

**Issue by Xionet** [emymin/EmyChess#5]
As soon as I try to import emychess into a VCC (vrchat creator companion) project, Unity immediately pops up its crash window and proceeds to crash the project. If I then open the project back up, A prefab message saying something about unpacking will persist and not go away unless I remove emychess from the files and then re-launch the project. I know this hasnt been updated since back in 2021 but it's one of the higher quality free chess boards that I love using. If you could fix it/update it that would be amazing~

**Comment by emymin** [comment]
Hello! I can't replicate the crash, however the message about unpacking prefabs is indeed there, seems to be due to a change in how UdonSharp handles nested prefabs.

If you just keep clicking "cancel" a lot of times, the message does go away and the prefab seems to work properly.

To actually fix the issue, I think I will be trying to migrate the prefab to VCC as soon as I can!

**Comment by Xionet** [comment]
I think the crash may have been due to incompatibility with another package I tried to import that had crashed unity but left a bunch of folders still in the project, so I will be trying again here in a bit and ahhhh ok, I was going to try and click cancel a bunch of times but I have my mouse setup to auto navigate to buttons and it would always auto navigate back onto the open prefab button, which makes rapid clicking cancel near impossible but I will try to import emychess again and see if it works and thanks for the possible migration to VCC! ^-^ You legit have the only chess board that not only has fun features with it's anarchy mode and the timer but are as far as I can tell, the only one that has it for free.

**Comment by emymin** [comment]
#6 with this update the prefab has been updated to a VRChat Package Manager package and to be fully compatible with UdonSharp 1.0+, which should solve the issue
