### ISSUE TITLE
Not Work?

### ISSUE THREAD

**Issue by Kaijudo11** [emymin/EmyChess#7]
I'm new to Udon side of things when it comes to VRChat so I could just be doing something wrong. I followed your directions for adding the prefab to my world, but when I go to test build none of the buttons seem to work and I can't start  Chess match. I'm using the the VRChat Creator Companion; with everything up to date

**Comment by emymin** [comment]
Hello! If you go in the Console tab in Unity and click Clear, do any errors remain? If so, what do they say?

**Comment by Kaijudo11** [comment]
I have good news!
I went into the console and clicked clear, no errors remained :)
Then I decide to start a new project, but this time I clicked the "Udon" tab instead of "World" like I normally do and the Chess Board now works in my test build :)

I will update you if I have any other issues.

Thank you so much for putting your time and effort into making this Chess Board, it's really great!

**Comment by emymin** [comment]
Nice! Yeah you have to use the UdonSharp template when creating a project (or import the UdonSharp package separately in the VRChat Creator Companion, before importing the EmyChess package) for it to work!
